### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by iProgYou** [michaellau4/FiveStars#1]
- [ ] Should have 7 MVPs.
    - [ ] 3 of those are User Auth, Heroku, and Production README.
    - [ ] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points
## Comments

**Comment by iProgYou** [comment]
Looks good, but just correct the above

**Comment by iProgYou** [comment]
- You will likely want to do Reviews and ratings before search and filters
